---
name: Set-ArrayAlt
version: 1.00
author:
  - 'Sullivan Beck <sbeck@cpan.org>'
abstract: arrays as objects with list/set operations
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Sort::DataTypes: 0
  perl: 5.6.0
provides:
  Set::ArrayAlt:
    file: lib/Set/ArrayAlt.pm
    version: 1.00
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
